"""
services/transcript/youtube.py
-------------------------------
Fetches captions from YouTube using youtube-transcript-api >= 1.0.

v1.x API changes vs 0.6.x:
  - YouTubeTranscriptApi is now instantiated (not used as static class)
  - api.fetch(video_id, languages=[...]) replaces list_transcripts() + .fetch()
  - Segments are FetchedTranscriptSnippet objects with .text / .start / .duration
    attributes (not dicts) — we normalise them to dicts here so the rest of the
    codebase stays unchanged.
  - api.list(video_id) replaces list_transcripts() for listing available langs.

Average latency: ~300-600ms per video (no download, just caption XML fetch).
"""
from __future__ import annotations

import logging
import re
from typing import TypedDict

from youtube_transcript_api import (
    YouTubeTranscriptApi,
    NoTranscriptFound,
    TranscriptsDisabled,
)

from core.exceptions import TranscriptUnavailableError, VideoFetchError

logger = logging.getLogger(__name__)

# Single instance reused across all requests (thread-safe, stateless)
_api = YouTubeTranscriptApi()


class TranscriptSegment(TypedDict):
    text: str
    start: float
    duration: float


# ── Video ID extraction ───────────────────────────────────────────────────────

def extract_video_id(url: str) -> str:
    """
    Pull the video ID out of any standard YouTube URL format:
      - https://youtube.com/watch?v=dQw4w9WgXcQ
      - https://youtu.be/dQw4w9WgXcQ
      - https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=30s
      - https://youtube.com/shorts/dQw4w9WgXcQ
    """
    patterns = [
        r"youtube\.com/watch\?.*v=([a-zA-Z0-9_-]{11})",
        r"youtu\.be/([a-zA-Z0-9_-]{11})",
        r"youtube\.com/embed/([a-zA-Z0-9_-]{11})",
        r"youtube\.com/shorts/([a-zA-Z0-9_-]{11})",
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    raise VideoFetchError(f"Could not extract video ID from YouTube URL: {url}")


# ── Transcript fetch ──────────────────────────────────────────────────────────

def _snippets_to_segments(fetched) -> list[TranscriptSegment]:
    """
    Normalise FetchedTranscriptSnippet objects → plain dicts.
    This keeps get_hook_transcript / get_full_transcript unchanged.
    """
    return [
        {"text": s.text, "start": s.start, "duration": s.duration}
        for s in fetched
    ]


def fetch_transcript(video_id: str) -> list[TranscriptSegment]:
    """
    Fetch the transcript for a YouTube video using the v1.x API.

    Strategy:
      1. Try English (manual + auto) via languages=[...] preference list.
      2. If no English transcript exists, fall back to whatever is available
         by fetching without a language filter.

    Returns a list of normalised segments: [{text, start, duration}, ...]
    Raises TranscriptUnavailableError if no captions exist at all.
    """
    try:
        # Preferred: English (manual preferred over auto-generated by the library)
        try:
            fetched = _api.fetch(video_id, languages=["en", "en-US", "en-GB"])
        except (NoTranscriptFound, Exception):
            # Fallback: any available language
            logger.info(
                "[YouTube] English transcript not found for %s — trying any language.",
                video_id,
            )
            fetched = _api.fetch(video_id)

        segments = _snippets_to_segments(fetched)
        logger.info(
            "[YouTube] Fetched %d transcript segments for %s", len(segments), video_id
        )
        return segments

    except TranscriptsDisabled:
        raise TranscriptUnavailableError("YouTube video")
    except NoTranscriptFound:
        raise TranscriptUnavailableError("YouTube video")
    except (TranscriptUnavailableError, VideoFetchError):
        raise
    except Exception as exc:
        exc_str = str(exc).lower()
        if "no element found" in exc_str or "could not retrieve" in exc_str:
            raise TranscriptUnavailableError(
                "YouTube video — captions may be disabled or in an unsupported format"
            )
        if "unavailable" in exc_str or "private" in exc_str:
            raise VideoFetchError(f"YouTube video {video_id} is unavailable or private.")
        logger.error("[YouTube] Unexpected transcript error for %s: %s", video_id, exc)
        raise VideoFetchError(f"Failed to fetch YouTube transcript: {exc}")


# ── Text helpers ──────────────────────────────────────────────────────────────

def get_hook_transcript(segments: list[TranscriptSegment], seconds: float = 5.0) -> str:
    """
    Return the spoken text from the first `seconds` of the video.
    Includes any segment that starts before the cutoff (avoids mid-word cuts).
    """
    hook_parts = [seg["text"].strip() for seg in segments if seg["start"] < seconds]
    return " ".join(hook_parts).strip()


def get_full_transcript(segments: list[TranscriptSegment]) -> str:
    """Join all segment text into a single clean string."""
    return " ".join(seg["text"].strip() for seg in segments).strip()
